image: gitpod/workspace-full-vnc:latest

ports:
  - port: 6080

tasks:
  - init: |
    sudo apt-get update
    sudo apt-get install -y firefox matchbox twm
    sudo apt-get clean && sudo rm -rf /var/cache/apt/* && sudo rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
  - command: |
    firefox https://www.youtube.com/watch?v=D41zSHJthZI
